displayName=Pet Training
author=Rosalyn Reardon-Leaman
description=Let's your pet learn and gain skills from watching you train
tags=pet,exp,skill
version=
plugins=com.PetTraining.PetTrainingPlugin
build=standard